### ISSUE TITLE
Change placement on status bar

### ISSUE THREAD

**Issue by Otiel** [tomoki1207/selectline-statusbar#4]
I have trouble placing the component exactly where I want on the status bar (see red arrow below). I have set `"selectline.alignment": "right"`. 

`"selectline.statusbarPriority": 100` places it too far too the left, while `"selectline.statusbarPriority": 99` places it too far to the right. Comma values do not seem to be supported. Is there any way to get the placement I want?

![image](https://user-images.githubusercontent.com/3851902/32540004-979216b0-c46b-11e7-89a2-6915ed05201c.png)

**Comment by tomoki1207** [comment]
Thank you for reporting.

Unfortunately, we can't handle the place as you want.
The `selectline.statusbarPriority` is used as a `priority` param at [StatusBarItem](https://code.visualstudio.com/docs/extensionAPI/vscode-api#StatusBarItem).
And may be the statusbaritems between 2 blue arrows have same priority, 100. 
In case of exists duplicate priorities, only VSCode knows how will be order.

**Comment by Otiel** [comment]
I was afraid that was the issue here. Thanks for confirming. I might open an issue on https://github.com/Microsoft/vscode and see if they can change the priority of the default items of the status bar.

**Comment by Otiel** [comment]
Created [#38620](https://github.com/Microsoft/vscode/issues/38620).
