### ISSUE TITLE
Selected Items count

### ISSUE THREAD

**Issue by kenkit** [tomoki1207/selectline-statusbar#7]
How do we get the number of selected characters ?
I think that is an important feature, notepad already has it.

**Comment by kanlukasz** [comment]
This is native option in VSCode. Just look at the status bar:

![obraz](https://user-images.githubusercontent.com/30685349/73381119-82e11100-42c5-11ea-9f59-f3cca476105f.png)

**Comment by kenkit** [comment]
Nice, thanks
